Add database types
monero-rs/monero-rs pull request #138
Opened 2022-12-17 16:20 UTC by Boog900

closes #128 

I have added a new feature ("database") for these types

2023-03-01 12:52 UTC, Boog900 commented
Hi @h4sh3d I think this is ready to be merged if there is anything you would like me to change let me know :)

2023-03-02 07:08 UTC, h4sh3d requested changes
Yep, almost ready to be merged.

Can you also add a new step in ci/build job after 'Build (experimental)' for only building with database feature.

2023-03-02 07:08 UTC, h4sh3d commented on src/lib.rs
> +//#[cfg(feature = "database")]
Uncomment here

2023-04-08 19:51 UTC, Boog900 commented
Closing as I have decided to define these types outside of monero-rs

2023-04-08 19:51 UTC, closed without merging