Adds fallible try_serialize
monero-rs/monero-rs pull request #48
Opened 2021-06-10 11:12 UTC by sdbondi

Add a fallible `try_serialize` function that returns an error if the underlying `Encodable` impl errors

This is useful in cases the user may not be/want to be aware of all failure case for applicable implementations
of `Encodable`. With untrusted input, without protections from the user, `serialize` allows external parties to 
cause a panic. `try_serialize` forces the user to consider this.

For example, passing `TxIn::ToScript` causes a panic in `serialize`.

2021-06-23 07:43 UTC, h4sh3d approved these changes
LGTM

2021-06-24 01:14 UTC, thomaseizinger requested changes
I've audited all `Encodable` implementations and the only one that fails for reasons other than actual IO is the one used in the newly added test.

I haven't dug into the details but if it is impossible to serialize this variant, why does it even exist? The documentation also states that it is not used - why do we have it @h4sh3d ? :D

Overall, the reason why `consensus_encode()` was previously unwrapped is because `io::Write` on a `Vec<u8>` never fails.

I think there is are better ways forward:

1. We completely remove the panicking implementation of `serialize` and always return a `Result`. By doing that, we allow implementations of `Encodable` to return errors other than the one from `io::Write`. This is an easy path forward but results in a slightly less convenient API.
2. We fix the implementation of `Encodable` on `TxIn` to not error and clearly document that implementations of `Encodable` MUST NOT return errors other than those produced by `io::Write`. This option allows us to use `unwrap` in `serialize`.
3. We introduce a dedicated `Error` for `Encodable` that differentiates between `io::Error`s and other failure causes. This would allow us to `panic!` on all `io::Error`s in `serialize` (because `Vec<u8>` can never hit them) and return a narrower set of errors for things the user actually needs to care about and should handle when calling `serialize`. This option is the most correct (assuming we want to retain the current behaviour of `Encodable` on `TxIn`) but also the most work.

I have no opinion on which one of the three we choose but I think we should choose one over the current implementation because the current `serialize` implementation is clearly not safe to use.

2021-06-24 06:41 UTC, sdbondi commented
@thomaseizinger Thanks for looking into this and the great assessment of the options 👍 

Here is my 2 cents (I'm writing this as I'm thinking about the problem - apologies for the length of it 😃 ):

1. Type-safe serialization can be infallible when used with a more restricted interfaces. However, since Encodable is a public trait we cannot predict the needs of implementors - so I think there is no avoiding the need to return a Result.

2. In this case, IMO the Encodable trait would need to reflect this. i.e  `consensus_encode` must not return an error. Which follows that an infallible `io::Write` impl must be used - since there is no way to set that as a trait bound on `W` we would probably have to make the trait function less generic i.e. take in`&mut Vec<u8>`. This also will likely result in implementations adding panics if they need to fail (the reasons to do this should be rare, but as we've seen already exist).

3. Agree that this is the most correct. Another 'intermediate' error type for encodable impls doesn't seem ideal, but definitely works. I question whether there is any practical benefit to excluding IO errors from the possible error variants when using `serialize`. Including it also has the benefit that the internal implementation could use a different (potentially fallible) `io::Write` impl without breaking the public API.  

After these thoughts, 1 is my preference (easy to implement, safe, less ergonomic), 3 is second (safe, doesnt include an 'impossible' error variant, another public error type, less ergonomic) and number 2 with the trait change and a correct impl MUST NOT panic rule (ergonimic, non breaking change, user needs to audit impls for panics, breaking change).

2021-06-24 07:37 UTC, h4sh3d commented
> I haven't dug into the details but if it is impossible to serialize this variant, why does it even exist? The documentation also states that it is not used - why do we have it @h4sh3d ? :D

These two variants comes from the CryptoNote specs to allow some scripting capabilities, but have never been used in Monero. When decoded the two variants match:
```rust
0x0 | 0x1 => Err(Error::ScriptNotSupported.into()),
```

The implementation of `Encodable for TxIn` is not correct regarding what's `Encodable` requires, we should not error for this. Either we serialize with `0x0` and `0x1` (I don't like it as it'd be probably incomplete solution) or we remove these two variants (I'm for it). I putted them here for completeness at the beginning but there is no good reason to keep them today IMO.

I'm not sure about the rest, serialization should not failed so changing its interface to return an error is very inconvenient, but at the same time I created an example with `TxIn` were the contract is not respected and `serialize` is not safe anymore, and this can happen outside of this library too as mentioned by @sdbondi.

I have no opinion on which one of the three we choose for now, but I'll keep thinking about it.

2021-06-28 10:29 UTC, sdbondi commented
I think that if we fix `Encodable` for `TxIn`, removing the variants makes sense to me as @h4sh3d said, we can close this. 
It makes sense to me that there should always be a way to represent a type as bytes without failure (aside from errors from impl `Write`) and a correct implementation would never need to return its own errors.
Re-open if anyone disagrees.

2021-06-28 10:29 UTC, closed without merging

2021-06-28 10:44 UTC, thomaseizinger commented
>     1. However, since Encodable is a public trait we cannot predict the needs of implementors

To fix this, we should probably seal the trait.